version: "3"

services:
  
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana-storage:/var/lib/grafana

  grafana-loki:
    image: grafana/loki
    ports:
      - 3100:3100
    # volumes:
    #   - ./\:/etc/loki/local-config.yaml